servers = [
  {
    hostname: "itcmaster001",
    replicas: 1,
    ip: "192.168.0.114",
    box: "rockylinux/9",
    #box: "shekeriev/debian-11",
    ram: 2048,
    cpu: 2
  },
  {
    hostname: "itcworker001",
    replicas: 1,
    ip: "192.168.0.115",
    box: "rockylinux/9",
    # box: "shekeriev/debian-11",
    ram: 2048,
    cpu: 4
  }
]

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false   # This config is not recomendable
  config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true # Use vbox 6.1.4 instead
  servers.each_with_index do |server, index|
    vm_name = format("node-%02d", index + 1) # Format the VM name as "node-01" style
    config.vm.define "node-#{index + 1}" do |node| # Set the VM name as "node-X"
      node.vm.box = server[:box]

      #Configure a Bridged Adapter and Assign a static IP address to each instance
      node.vm.network "public_network", bridge: "eth0", type: "static", ip: server[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.name = vm_name # Set the machine name
        vb.memory = server[:ram]
        vb.cpus = server[:cpu]
      end

      # Set the hostname of the VM
      node.vm.hostname = server[:hostname]

      node.vm.provision "shell", inline: <<-SHELL
        sudo yum upgrade -y # Add the sudo apt upgrade command
      SHELL

      # Create the "sw_admin" user
      node.vm.provision "shell", inline: <<-SHELL
        sudo useradd -m -s /bin/bash swadmin
        echo "swadmin:swadmin" | sudo chpasswd
        sudo usermod -aG wheel swadmin
      SHELL

    end
  end
end
