servers = [
  {
    hostname: "itcmaster",
    replicas: 3,
    ip: "192.168.0.114",
    box: "ubuntu/trusty64",
    ram: 2048,
    cpu: 2
  },
  {
    hostname: "itcworker",
    replicas: 2,
    ip: "192.168.0.120",
    box: "ubuntu/trusty64",
    ram: 2048,
    cpu: 4
  }
]

Vagrant.configure("2") do |config|
  servers.each do |server|
    server[:replicas].times do |index|
      ip_suffix = index
      vm_name = format("node-%02d-%s%02d", index + 1, server[:hostname], ip_suffix)
      ip_parts = server[:ip].split('.')
      ip_parts[-1] = (ip_parts[-1].to_i + ip_suffix).to_s
      ip = ip_parts.join('.')
      
      config.vm.define vm_name do |node|
        node.vm.box = server[:box]
        node.vm.network "public_network", bridge: "eth0", type: "static", ip: ip

        node.vm.provider "virtualbox" do |vb|
          vb.name = vm_name
          vb.memory = server[:ram]
          vb.cpus = server[:cpu]
        end

        node.vm.hostname = "#{server[:hostname]}#{format("%02d", ip_suffix)}"

        node.vm.provision "shell", inline: <<-SHELL
          sudo useradd -m -s /bin/bash swadmin
          echo "swadmin:swadmin" | sudo chpasswd
          sudo usermod -aG sudo swadmin
        SHELL

        node.vm.provision "shell", inline: <<-SHELL
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get autoremove -y
        SHELL
      end
    end
  end
end
